Correct link library order for mm2gv
The sparse lib depends on many of the libs that were listed before it.

An upcoming change to lib/gvc revealed this and without this change,
the following link error would occur:

../../lib/sparse/libsparse.a(SparseMatrix.c.o): In function `SparseMatrix_page_rank':
SparseMatrix.c:(.text+0x12471): undefined reference to `Verbose'