ortho: CMake: ensure ortho symbols are exported from gvc
The object modules from the static ortho lib are statically linked
into the gvc shared lib which means that its symbols should be
exported from gvc instead of imported. Defining GVC_EXPORTS achieves
this.

Fixes errors like this with MinGW:

C:/tools/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../ortho/CMakeFiles/ortho_obj.dir/fPQ.c.obj:fPQ.c:(.text+0x6d): undefined reference to `__imp_gcalloc'