common: remove weak declaration of drand48 that causes it to be undefined with MinGW
Fixes this error with MinGW:

C:/tools/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot export drand48: symbol not defined
C:/tools/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../ortho/CMakeFiles/ortho_obj.dir/partition.c.obj:partition.c:(.text+0x4de): undefined reference to `drand48'

Towards https://gitlab.com/graphviz/graphviz/-/issues/2102.