label: CMake: ensure label symbols are exported from the gvc lib
The object modules from the static label lib are statically linked
into the gvc shared lib through the common object library which means
that their symbols should be exported from gvc instead of
imported. Defining GVC_EXPORTS achieves this.

This is what the autotools build already does.

Fixes this error with MinGW:

C:/tools/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../label/liblabel.a(xlabels.c.obj):xlabels.c:(.text+0x98): undefined reference to `__imp_zmalloc'
C:/tools/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../label/liblabel.a(xlabels.c.obj):xlabels.c:(.text+0x1f40): undefined reference to `__imp_zmalloc'